version: '3.7'

services:
  api:
    build:
      context: .
    container_name: lab_6_api
    working_dir: /app
    restart: unless-stopped
    ports:
      - '4000:4000'

    volumes:
      - ./:/app
      - /app/node_modules

  
  db:
    image: postgres
    command: postgres -c 'max_connections=200'
    container_name: lab_6_db
    restart: always
    environment:
      POSTGRES_DB: student_db
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@test.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - '7777:80'
volumes:
  pgdata:
